/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721G__factory } from "./ERC721G__factory";
export { IERC721G__factory } from "./IERC721G__factory";
