/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as standards from "./standards";
export type { standards };
export type { TheKoreans1945 } from "./TheKoreans1945";
export type { TheKoreans1945Minter } from "./TheKoreans1945Minter";
