/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as standards from "./standards";
export { TheKoreans1945__factory } from "./TheKoreans1945__factory";
export { TheKoreans1945Minter__factory } from "./TheKoreans1945Minter__factory";
